# 데이터 추가 및 데이터셋 정리

In [ ]:
import os, sys
import pandas as pd
import numpy as np
from numpy import loadtxt
from collections import deque

## 1. 추가된 앉는 모션 데이터들을 하나의 txt파일로 만들기
* 더불어, 해당 데이터의 y 라벨링 추가함
* [참고] 라벨링 번호 의미

1.   걷기 (위로 계단오르기, 아래로 계단 오르기 모두)
2.   서있기
3.   눕기
4.   앉기 (섰다가 앉기, 앉았다가 서기 모두)

In [ ]:
# 각각의 앉기(label = 4) 파일을 하나의 txt 파일로 묶기 
file_path = '/content/drive/MyDrive/motion_dataset/'
sitting_path = file_path + 'sitting/'

# sitting 폴더 내 모든 txt파일 이름 sitlist에 저장
sitlist = os.listdir(sitting_path)
sitlist = sitlist [:-1] # 마지막에 .ipynb 파일 하나가 생성되었길래 제거.

# blabla_42.txt가 마지막임을 확인
sitlist[-1]

In [ ]:
# 모든 txt를 불러오면서 하나의 array로 concatenate 하기
datalist = np.empty((1,6))  # 빈 다차원 배열 만들기 ( = [] 하면 에러남)
for i in sitlist:
  data = np.loadtxt(sitting_path + i)
  datalist = np.concatenate((datalist,data))

# 맨 처음 empty 행은 지워주기
# 최종 shape이 (14858, 6)
# 첫 행의 모양이 [ 1.92,-9.18999,-0.13999,0.51969296,1.1646136,0.24540055]
# 이면 성공
datalist = np.delete(datalist, (0), axis = 0)
print(datalist.shape)
print(datalist)

(14858, 6)
[[ 1.92       -9.18999    -0.13999     0.51969296  1.1646136   0.24540055]
 [ 1.93       -9.26999    -0.15999     0.5156184   1.1564646   0.15576075]
 [ 1.93       -9.34999    -0.18999     0.49932024  1.1768372   0.05389733]
 ...
 [ 7.66       -5.85999     4.51       -4.544956   -3.8226192   5.9334536 ]
 [ 7.8        -5.88999     4.48       -4.337155   -3.6107433   6.389802  ]
 [ 7.98       -5.92999     4.45       -4.324931   -2.7387924   6.952088  ]]


In [ ]:
# 앉기 데이터 x 저장
np.savetxt(sitting_path + 'trainx_sit_all.txt', datalist, delimiter=" ")

# # 앉기 데이터 제대로 저장되었는지 다시 열어서 확인
# # google drive에도 제대로 저장되었음 확인(2022-01-24)
# temp = np.loadtxt(sitting_path + 'trainx_sit_all.txt', delimiter=" ")
# print(temp)
# print(temp.shape)

In [ ]:
# 모든 행마다 마지막 열에 앉기 데이터임을 표시하는 label = 4 넣기
